spring:
  application:
    name: playchild
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/wise-study?serverTimezone=Asia/Seoul
    username: root
    password: admin1!
# JPA 설정
  jpa:
    hibernate:
      ddl-auto: none        # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        format_sql: true      # 쿼리 로그 포맷 (정렬)
        show_sql: true        # 쿼리 로그 출력
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liA9hB0a4ySMsJDl
            client-secret: 35462a7f4adb11642c500eb42be37c6f506f7c1e